#fatima bilal
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: NodePort
  selector:
    component: auth
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: classrooms-svc
spec:
  type: NodePort
  selector:
    component: classrooms
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  type: NodePort
  selector:
    component: client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-svc
spec:
  type: NodePort
  selector:
    component: event-bus
  ports:
    - protocol: TCP
      port: 4009
      targetPort: 4009
---
apiVersion: v1
kind: Service
metadata:
  name: post-svc
spec:
  type: NodePort
  selector:
    component: post
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
#fatima bilal
