apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
        - name: auth
          image: fatima71459/auth
          ports:
            - containerPort: 4000
        - name: classrooms
          image: fatima71459/classrooms
          ports:
            - containerPort: 4001
        - name: client
          image: fatima71459/client
          ports:
            - containerPort: 5000
        - name: event-bus
          image: fatima71459/event-bus
          ports:
            - containerPort: 4009
        - name: post
          image: fatima71459/post
          ports:
            - containerPort: 4002
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: my-pvc
